title: Archit Shenoy's Github Portfolio
logo: assets/img/ArchiteGithub.png
description: > #description
  I am an aspiring tennis athlete and student at Mission San Jose High School, Fremont, CA.
  <br>
  My goal is to put in the maximum effort and learn as much as I can both in my chosen sport and in academics.

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
